// Auto-generated by deploy-perp-testnet.ts (kubTestnet, 2026-07-07T16:56:08.824Z)
window.XKUB_CONFIG = {
  "chainId": 25925,
  "chainName": "Bitkub Chain Testnet",
  "rpcUrl": "https://rpc-testnet.bitkubchain.io",
  "explorer": "https://testnet.kubscan.com",
  "kusdtDecimals": 18,
  "addresses": {
    "KUSDT": "0xB16F025234661aFE6Ab43EEEE8e5a688122C3D0c",
    "XKubPriceOracle": "0xe9ae932D4b14B3B59f63F035b8E114815374fD15",
    "XKubPerpPool": "0xb677BB936DB2bA58abCef806c9BAc531c585A67B",
    "XKubPerpMarket": "0xC4AAe01ff758dD4fb9DC05a23Bc081deDBcC7a2e",
    "XKubPerpRouter": "0x0620cAe574afA4AAFaB7B110eaCBf1E024DBD036",
    "XKubReferral": "0xceb43c3055F99c85aA65B3B51C0DaA8fC0cb0a86"
  },
  "multicall3": "0x1421cb2dFA99A369ad162C83E0ACc171C951c204",
  "relayerUrl": "https://xkub-keeper.onrender.com/order",
  "markets": [
    {
      "symbol": "BTC",
      "maxLeverageX": 40
    },
    {
      "symbol": "ETH",
      "maxLeverageX": 25
    },
    {
      "symbol": "KUB",
      "maxLeverageX": 10
    }
  ],
  "feeTiers": [
    {
      "tier": 0,
      "name": "Standard",
      "discountBps": 0,
      "volumeUsd": 0
    },
    {
      "tier": 1,
      "name": "VIP 1",
      "discountBps": 1000,
      "volumeUsd": 50000
    },
    {
      "tier": 2,
      "name": "VIP 2",
      "discountBps": 2500,
      "volumeUsd": 250000
    },
    {
      "tier": 3,
      "name": "VIP 3",
      "discountBps": 5000,
      "volumeUsd": 1000000
    }
  ],
  "basePositionFeeBps": 3,
  "referredDiscountBps": 1000
};
