// Auto-generated by deploy-perp-testnet.ts (localhost, 2026-07-07T09:43:22.546Z)
window.XKUB_CONFIG = {
  "chainId": 31337,
  "chainName": "Bitkub Chain Testnet",
  "rpcUrl": "http://127.0.0.1:8545",
  "explorer": "",
  "kusdtDecimals": 18,
  "addresses": {
    "KUSDT": "0x6718b9232B15d61C602a7C60acfF41606c129Abb",
    "XKubPriceOracle": "0x3380B63bac55501492Aff80f2d7eF5c171909AE1",
    "XKubPerpPool": "0x79C29972195808E156674B1407D6D0d8516a72bD",
    "XKubPerpMarket": "0xFe6543D91309b23f73EdB59f0dc98BF6f012D03F",
    "XKubPerpRouter": "0xdD0AEF74980C0d8Ac8b547c80E93895E11fE9Cbe",
    "XKubReferral": "0xbC373a3a2A2cb66772b6d3e1E8714a631a1F6670"
  },
  "markets": [
    {
      "symbol": "BTC",
      "maxLeverageX": 10
    },
    {
      "symbol": "ETH",
      "maxLeverageX": 10
    },
    {
      "symbol": "KUB",
      "maxLeverageX": 5
    }
  ],
  "feeTiers": [
    {
      "tier": 0,
      "name": "Standard",
      "discountBps": 0
    },
    {
      "tier": 1,
      "name": "VIP 1",
      "discountBps": 1000
    },
    {
      "tier": 2,
      "name": "VIP 2",
      "discountBps": 2500
    },
    {
      "tier": 3,
      "name": "VIP 3",
      "discountBps": 5000
    }
  ]
};
