// Auto-generated by deploy-perp-testnet.ts (localhost, 2026-07-07T10:28:22.686Z)
window.XKUB_CONFIG = {
  "chainId": 31337,
  "chainName": "Bitkub Chain Testnet",
  "rpcUrl": "http://127.0.0.1:8545",
  "explorer": "",
  "kusdtDecimals": 18,
  "addresses": {
    "KUSDT": "0x7110C8951d17B69054395742e265bbd98259564A",
    "XKubPriceOracle": "0x4df32DB96Fe6820520023FA5e5388E5486081bCd",
    "XKubPerpPool": "0xB1ddb71275C2833D15cbd34Adb36a0643783d7fA",
    "XKubPerpMarket": "0x9BeA381ab97Df2F10216C525D821412d8CAE0001",
    "XKubPerpRouter": "0x51A693EB9846287bfE57485eC1B3F8b3F71cC086",
    "XKubReferral": "0x22121af9EB1C2e8B670Fe8c1173Bfe2B45737972"
  },
  "markets": [
    {
      "symbol": "BTC",
      "maxLeverageX": 40
    },
    {
      "symbol": "ETH",
      "maxLeverageX": 25
    },
    {
      "symbol": "KUB",
      "maxLeverageX": 10
    }
  ],
  "feeTiers": [
    {
      "tier": 0,
      "name": "Standard",
      "discountBps": 0,
      "volumeUsd": 0
    },
    {
      "tier": 1,
      "name": "VIP 1",
      "discountBps": 1000,
      "volumeUsd": 50000
    },
    {
      "tier": 2,
      "name": "VIP 2",
      "discountBps": 2500,
      "volumeUsd": 250000
    },
    {
      "tier": 3,
      "name": "VIP 3",
      "discountBps": 5000,
      "volumeUsd": 1000000
    }
  ],
  "basePositionFeeBps": 3,
  "referredDiscountBps": 1000
};
